# frozen_string_literal: true

Theirrecipe.create!([
                      { page_id: 1, name: 'Acorn squash caramelized onion goat cheese pizza' },
                      { page_id: 2, name: 'Asparagus avocado sushi' },
                      { page_id: 3, name: 'Bacon egg and spinach fried rice' },
                      { page_id: 4, name: 'Bacon herb and cheese star bread' },
                      { page_id: 5, name: 'Baked potatoes' },
                      { page_id: 6, name: 'Baked scotch eggs' },
                      { page_id: 7, name: 'Beef stew in red wine sauce' },
                      { page_id: 8, name: 'Beef stew with dumplings' },
                      { page_id: 9, name: 'Beef tenderloin steaks with celert root gratin' },
                      { page_id: 10, name: 'Bibimbap' },
                      { page_id: 11, name: 'Blueberry vanilla cake' },
                      { page_id: 12, name: 'Bouillabaisse' },
                      { page_id: 13, name: 'Braised lamb with herb scented jus' },
                      { page_id: 14, name: 'Caramel cookies' },
                      { page_id: 15, name: 'Caramelised onions' },
                      { page_id: 16, name: 'Cassoulet with duck confit' },
                      { page_id: 17, name: 'Chicken pesto pene with bacon and feta' },
                      { page_id: 18, name: 'Cheese and ham omelette' },
                      { page_id: 19, name: 'Chicken noodle soup' },
                      { page_id: 20, name: 'Chocolate cake' },
                      { page_id: 21, name: 'Chocolate macarons' },
                      { page_id: 22, name: 'Cream cheese and jalapeno stuffed chicken breast' },
                      { page_id: 23, name: 'Creamy scallop fettuccine with lemon and capers' },
                      { page_id: 24, name: 'Creamy tomato soup' },
                      { page_id: 25, name: 'Devonshire honey cake' },
                      { page_id: 26, name: 'Dinner rolls' },
                      { page_id: 27, name: 'Firecracker shrimp' },
                      { page_id: 28, name: 'Fruit clafoutis' },
                      { page_id: 29, name: 'Garlic butter steak and potatoes' },
                      { page_id: 30, name: 'Grilled chicken salad with cabbage' },
                      { page_id: 31, name: 'Grilled oysters' },
                      { page_id: 32, name: 'Honey and mustard roast gammon' },
                      { page_id: 33, name: 'Honey mustard chicken thighs with argula' },
                      { page_id: 34, name: 'Honey tamarind baby back ribs' },
                      { page_id: 35, name: 'Hunters sausage and sauerkraut stew' },
                      { page_id: 36, name: 'Injera' },
                      { page_id: 37, name: 'Lembas bread' },
                      { page_id: 38, name: 'Lemon pie' },
                      { page_id: 39, name: 'Mars bar cake' },
                      { page_id: 40, name: 'Marshmallow crispie bars' },
                      { page_id: 41, name: 'Moroccan braised chicken' },
                      { page_id: 42, name: 'Mussels and clams in a spicy tomato broth' },
                      { page_id: 43, name: 'Over the top mushroom quiche' },
                      { page_id: 44, name: 'Paella' },
                      { page_id: 45, name: 'Pan roast salmon with tomato viniagrette' },
                      { page_id: 46, name: 'Pancakes' },
                      { page_id: 47, name: 'Parmesan and garlic crusted potato wedges' },
                      { page_id: 48, name: 'Potato gnocchi with mushroom ragu' },
                      { page_id: 49, name: 'Potato wedges' },
                      { page_id: 50, name: 'Pull apart flauta ring' },
                      { page_id: 51, name: 'Roast chicken with aromatic jus' },
                      { page_id: 52, name: 'Roast leg of lamb' },
                      { page_id: 53, name: 'Russian honey cake' },
                      { page_id: 54, name: 'Samoa cookie inspired iced coffee' },
                      { page_id: 55, name: 'Seared scallops in a cream lemon caper sauce' },
                      { page_id: 56, name: 'Slow roasted pork loin with molasses and balsamic glaze' },
                      { page_id: 57, name: 'Spicy italian pizza' },
                      { page_id: 58, name: 'Spinache and artichoke dip stuffed garlic bread' },
                      { page_id: 59, name: 'Trout with garlic lemon butter herb sauce' },
                      { page_id: 60, name: 'Welsh rarebit' }
                    ])
