# frozen_string_literal: true

Theirrecipe.create!([
                      { name: 'Acorn squash caramelized onion goat cheese pizza' },
                      { name: 'Asparagus avocado sushi' },
                      { name: 'Bacon egg and spinach fried rice' },
                      { name: 'Bacon herb and cheese star bread' },
                      { name: 'Baked potatoes' },
                      { name: 'Baked scotch eggs' },
                      { name: 'Beef stew in red wine sauce' },
                      { name: 'Beef stew with dumplings' },
                      { name: 'Beef tenderloin steaks with celert root gratin' },
                      { name: 'Bibimbap' },
                      { name: 'Blueberry vanilla cake' },
                      { name: 'Bouillabaisse' },
                      { name: 'Braised lamb with herb scented jus' },
                      { name: 'Caramel cookies' },
                      { name: 'Caramelised onions' },
                      { name: 'Cassoulet with duck confit' },
                      { name: 'Chicken pesto pene with bacon and feta' },
                      { name: 'Cheese and ham omelette' },
                      { name: 'Chicken noodle soup' },
                      { name: 'Chocolate cake' },
                      { name: 'Chocolate macarons' },
                      { name: 'Cream cheese and jalapeno stuffed chicken breast' },
                      { name: 'Creamy scallop fettuccine with lemon and capers' },
                      { name: 'Creamy tomato soup' },
                      { name: 'Devonshire honey cake' },
                      { name: 'Dinner rolls' },
                      { name: 'Firecracker shrimp' },
                      { name: 'Fruit clafoutis' },
                      { name: 'Garlic butter steak and potatoes' },
                      { name: 'Grilled chicken salad with cabbage' },
                      { name: 'Grilled oysters' },
                      { name: 'Honey and mustard roast gammon' },
                      { name: 'Honey mustard chicken thighs with argula' },
                      { name: 'Honey tamarind baby back ribs' },
                      { name: 'Hunters sausage and sauerkraut stew' },
                      { name: 'Injera' },
                      { name: 'Lembas bread' },
                      { name: 'Lemon pie' },
                      { name: 'Mars bar cake' },
                      { name: 'Marshmallow crispie bars' },
                      { name: 'Moroccan braised chicken' },
                      { name: 'Mussels and clams in a spicy tomato broth' },
                      { name: 'Over the top mushroom quiche' },
                      { name: 'Paella' },
                      { name: 'Pan roast salmon with tomato viniagrette' },
                      { name: 'Pancakes' },
                      { name: 'Parmesan and garlic crusted potato wedges' },
                      { name: 'Potato gnocchi with mushroom ragu' },
                      { name: 'Potato wedges' },
                      { name: 'Pull apart flauta ring' },
                      { name: 'Roast chicken with aromatic jus' },
                      { name: 'Roast leg of lamb' },
                      { name: 'Russian honey cake' },
                      { name: 'Samoa cookie inspired iced coffee' },
                      { name: 'Seared scallops in a cream lemon caper sauce' },
                      { name: 'Slow roasted pork loin with molasses and balsamic glaze' },
                      { name: 'Spicy italian pizza' },
                      { name: 'Spinache and artichoke dip stuffed garlic bread' },
                      { name: 'Trout with garlic lemon butter herb sauce' },
                      { name: 'Welsh rarebit' }
                    ])
