TheirRecipe.create!([
  {page_id: 1, page_name: "Acorn squash caramelized onion goat cheese pizza"},
  {page_id: 2, page_name: "Asparagus avocado sushi"},
  {page_id: 3, page_name: "Bacon egg and spinach fried rice"},
  {page_id: 4, page_name: "Bacon herb and cheese star bread"},
  {page_id: 5, page_name: "Baked potatoes"},
  {page_id: 6, page_name: "Baked scotch eggs"},
  {page_id: 7, page_name: "Beef stew in red wine sauce"},
  {page_id: 8, page_name: "Beef stew with dumplings"},
  {page_id: 9, page_name: "Beef tenderloin steaks with celert root gratin"},
  {page_id: 10, page_name: "Bibimbap"},
  {page_id: 11, page_name: "Blueberry vanilla cake"},
  {page_id: 12, page_name: "Bouillabaisse"},
  {page_id: 13, page_name: "Braised lamb with herb scented jus"},
  {page_id: 14, page_name: "Caramel cookies"},
  {page_id: 15, page_name: "Caramelised onions"},
  {page_id: 16, page_name: "Cassoulet with duck confit"},
  {page_id: 17, page_name: "Chicken pesto pene with bacon and feta"},
  {page_id: 18, page_name: "Cheese and ham omelette"},
  {page_id: 19, page_name: "Chicken noodle soup"},
  {page_id: 20, page_name: "Chocolate cake"},
  {page_id: 21, page_name: "Chocolate macarons"},
  {page_id: 22, page_name: "Cream cheese and jalapeno stuffed chicken breast"},
  {page_id: 23, page_name: "Creamy scallop fettuccine with lemon and capers"},
  {page_id: 24, page_name: "Creamy tomato soup"},
  {page_id: 25, page_name: "Devonshire honey cake"},
  {page_id: 26, page_name: "Dinner rolls"},
  {page_id: 27, page_name: "Firecracker shrimp"},
  {page_id: 28, page_name: "Fruit clafoutis"},
  {page_id: 29, page_name: "Garlic butter steak and potatoes"},
  {page_id: 30, page_name: "Grilled chicken salad with cabbage"},
  {page_id: 31, page_name: "Grilled oysters"},
  {page_id: 32, page_name: "Honey and mustard roast gammon"},
  {page_id: 33, page_name: "Honey mustard chicken thighs with argula"},
  {page_id: 34, page_name: "Honey tamarind baby back ribs"},
  {page_id: 35, page_name: "Hunters sausage and sauerkraut stew"},
  {page_id: 36, page_name: "Injera"},
  {page_id: 37, page_name: "Lembas bread"},
  {page_id: 38, page_name: "Lemon pie"},
  {page_id: 39, page_name: "Mars bar cake"},
  {page_id: 40, page_name: "Marshmallow crispie bars"},
  {page_id: 41, page_name: "Moroccan braised chicken"},
  {page_id: 42, page_name: "Mussels and clams in a spicy tomato broth"},
  {page_id: 43, page_name: "Over the top mushroom quiche"},
  {page_id: 44, page_name: "Paella"},
  {page_id: 45, page_name: "Pan roast salmon with tomato viniagrette"},
  {page_id: 46, page_name: "Pancakes"},
  {page_id: 47, page_name: "Parmesan and garlic crusted potato wedges"},
  {page_id: 48, page_name: "Potato gnocchi with mushroom ragu"},
  {page_id: 49, page_name: "Potato wedges"},
  {page_id: 50, page_name: "Pull apart flauta ring"},
  {page_id: 51, page_name: "Roast chicken with aromatic jus"},
  {page_id: 52, page_name: "Roast leg of lamb"},
  {page_id: 53, page_name: "Russian honey cake"},
  {page_id: 54, page_name: "Samoa cookie inspired iced coffee"},
  {page_id: 55, page_name: "Seared scallops in a cream lemon caper sauce"},
  {page_id: 56, page_name: "Slow roasted pork loin with molasses and balsamic glaze"},
  {page_id: 57, page_name: "Spicy italian pizza"},
  {page_id: 58, page_name: "Spinache and artichoke dip stuffed garlic bread"},
  {page_id: 59, page_name: "Trout with garlic lemon butter herb sauce"},
  {page_id: 60, page_name: "Welsh rarebit"}
])
